# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Logic App infrastructure only, not the application
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "LogicAppDemo"
#  See ../Docs/Create-Variable-Group.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'

# ----------------------------------------------------------------------------------------------------
trigger: none

pr: none

#trigger:
#  branches:
#    include:
#    - main
#  paths:
#    exclude:
#      - '*'
#    include: 
#      - 'Infrastructure/**/*.yml'
#      - 'Infrastructure/**/*.bicep'

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/infra-only-pipe.yml
  parameters:
    variableGroupName: 'LogicAppDemo'
    environments: ['DEMO']
