# ----------------------------------------------------------------------------------------------------
# Template to deploy Azure Resources for one environment
# ----------------------------------------------------------------------------------------------------
parameters:
- name: variableGroupName
  default: 'myVariableGroup'
- name: environmentName
  default: 'DEV'
- name: templateFolderName
  default: 'infra/Bicep'
- name: templateFileName
  default: 'main.bicep'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: CreateInfra
  displayName: Initialize Create Infra
  environment: ${{ parameters.environmentName }}

- job: CreateInfraJob
  displayName: Create Infrastructure
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentNameUpper
      value: ${{ upper(parameters.environmentName) }}
    - name: environmentNameLower
      value: ${{ lower(parameters.environmentName) }}
    - name: templateFile
      value: '$(Pipeline.Workspace)/s/${{ parameters.templateFolderName }}/${{ parameters.templateFileName }}'
    - name: compiledJsonFile
      value: '${{ parameters.templateFolderName }}/compiled.json'

    # use the environment value to determine which resource group we should deploy to
    - ${{ if eq(variables.environmentNameUpper, 'DEV') }}:
      - name: resourceGroupName
        value: $(resourceGroupNameDev)
    - ${{ if eq(variables.environmentNameUpper, 'QA') }}:
      - name: resourceGroupName
        value: $(resourceGroupNameQA)
    - ${{ if eq(variables.environmentNameUpper, 'PROD') }}:
      - name: resourceGroupName
        value: $(resourceGroupNameProd)

  steps:
  - bash: |
      appNameLower=$(echo "$(appName)" | tr '[:upper:]' '[:lower:]')
      echo "appName=$(appName)"
      echo "appNameLower=$appNameLower"
      echo "##vso[task.setvariable variable=appNameLower]$appNameLower"

      resourceGroupNameWithEnv=$(echo "rg-$(appName)-$(environmentNameLower)" | tr '[:upper:]' '[:lower:]')
      echo "resourceGroupNameWithEnv=$resourceGroupNameWithEnv"
      echo "##vso[task.setvariable variable=resourceGroupNameWithEnv]$resourceGroupNameWithEnv"
      
      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
                                   
      runDateTimeZ=$(echo $(date '+%Y%m%dT%H%M%SZ'))
      echo "##vso[task.setvariable variable=runDateTimeZ]$runDateTimeZ"
      echo "runDateTimeZ=$runDateTimeZ"
    displayName: 'Create Variables'
    continueOnError: true

  - bash: |
      echo "azureSubscription=$(azureSubscription)"
      echo "createResourceGroup=$(createResourceGroup)"
      echo "resourceGroupName=$(resourceGroupName)"
      echo "resourceGroupNameDev=$(resourceGroupNameDev)"
      echo "resourceGroupNameQA=$(resourceGroupNameQA)"
      echo "resourceGroupNameProd=$(resourceGroupNameProd)"
      echo "environmentNameUpper=$(environmentNameUpper)"
      echo "environmentNameLower=$(environmentNameLower)"
      echo "region=$(region)"
      echo "appName=$(appName)"
      echo "appNameLower=$(appNameLower)"
      echo "keyVaultOwnerUserId=$(keyVaultOwnerUserId)"
      echo "runDateTime=$(runDateTime)"
      echo "runDateTimeZ=$(runDateTimeZ)"
      echo "templateFile=$(templateFile)"
      echo "Resource Group Command:"
      echo "  az group create --name $(resourceGroupName) --location $(region) --tags LastDeployed=$(runDateTime) Application=$(appPrefix) AppName=$(appName) Environment=$(environmentNameUpper)"
      echo "Bicep Deploy Sample Command:"
      echo "  az deployment group create -n main-deploy-$(runDateTimeZ) --resource-group $(resourceGroupName) --template-file 'main.bicep' --parameters environment=$(environmentNameUpper) appName=$(appName) keyVaultOwnerUserId=$(keyVaultOwnerUserId)"
      echo "Pipeline Workspace Directory Contents:"
      tree $(Pipeline.Workspace)
    displayName: 'Display Variables'
    continueOnError: true

  # Login is needed if you are pulling Bicep files from an Azure Container Registry
  # -script: az login --service-principal -u $(principalId) -p $(clientSecret) --tenant $(tenantId)
  #   displayName: 'az login'

  # - script: az bicep build --file $(templateFile) --outfile $(compiledJsonFile)
  #   displayName: 'Compile Bicep file'

  # - ${{ if or(eq(lower(parameters.createResourceGroup), 'true'), eq(parameters.createResourceGroup, '')) }}:
  - task: AzureCLI@2
    displayName: 'Create Resource Group'
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: az group create --name $(resourceGroupName) --location $(region) --tags LastDeployed=$(runDateTime) AppPrefix=$(appPrefix) AppName=$(appName) Environment=$(environmentNameUpper)

  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Publish Bicep Resources'
    inputs:
      csmFile: $(templateFile)
      overrideParameters: >
        -appName $(appName)
        -environmentCode $(environmentNameLower)
        -keyVaultOwnerUserId $(keyVaultOwnerUserId)
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: $(azureSubscription)
      action: 'Create Or Update Resource Group'
      resourceGroupName: $(resourceGroupName)
      location: $(region)
      templateLocation: 'Linked artifact'
      deploymentMode: 'Incremental'
