# ----------------------------------------------------------------------------------------------------
# Template to add Azure Secure DevOps Scan
# To enable this, you must add Azure DevOps Extension to your Azure DevOps Organization
# See https://marketplace.visualstudio.com/items?itemName=ms-securitydevops.microsoft-security-devops-azdevops
# ----------------------------------------------------------------------------------------------------
parameters:
- name: variableGroupName
  default: 'myVariableGroup'
- name: environmentName
  default: 'DEV'

# ----------------------------------------------------------------------------------------------------
jobs:
- deployment: SecurityScanDeployment
  displayName: Initialize Security Scan Deploy
  environment: ${{ parameters.environmentName }}

- job: SecurityScanJob
  displayName: Security Scan Job
  
  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: environmentName
      value: ${{ parameters.environmentName }}

  steps:
  - bash: |
      doDevOpsScan=$(echo "$(runSecurityDevOpScan)" | tr '[:upper:]' '[:lower:]')
      echo "##vso[task.setvariable variable=doDevOpsScan]$doDevOpsScan"
      doPsRuleScan=$(echo "$(runPsRuleScan)" | tr '[:upper:]' '[:lower:]')
      echo "##vso[task.setvariable variable=doPsRuleScan]$doPsRuleScan"
    displayName: 'Create Variables'
    continueOnError: true

  - bash: |
      echo "environmentName=$(environmentName)"
      echo "runSecurityDevOpScan=$(runSecurityDevOpScan)"
      echo "runPsRuleScan=$(runPsRuleScan)"
      echo "doDevOpsScan=$(doDevOpsScan)"
      echo "doPsRuleScan=$(doPsRuleScan)"
      echo "variables.doDevOpsScan=$(variables.doDevOpsScan)"
      echo "variables.doPsRuleScan=$(variables.doPsRuleScan)"
    displayName: 'Display Variables'

  # ----------------------------------------------------------------------------------------------------
  - ${{ if eq(lower(variables.doDevOpsScan), 'true') }}:
    - task: UseDotNet@2
      displayName: 'Use dotnet 3.1'
      inputs:
        version: 3.1.x
        
    - task: UseDotNet@2
      displayName: 'Use dotnet 6.0'
      inputs:
        version: 6.0.x

    - task: MicrosoftSecurityDevOps@1
      displayName: 'Run Microsoft Security DevOps'
      continueOnError: true

  # ----------------------------------------------------------------------------------------------------
  - ${{ if eq(lower(variables.doPsRuleScan), 'true') }}:
    - task: ps-rule-assert@2
      displayName: Run PSRule Analysis
      inputs:
        modules: 'PSRule.Rules.Azure'
        outputFormat: Sarif
        outputPath: reports/PSRuleOutput.sarif
      continueOnError: true

    - task: PublishBuildArtifacts@1
      displayName: Publish PSRule Results
      inputs:
        pathToPublish: reports/PSRuleOutput.sarif
        artifactName: CodeAnalysisLogs
      continueOnError: true
