# ----------------------------------------------------------------------------------------------------
# Template to build logic app standard artifacts
# ----------------------------------------------------------------------------------------------------
parameters: 
- name: variableGroupName
  default:  'myVariableGroup'
- name: environmentName
  default:  'DEV'

# ------------------------------------------------------------------------------------------------------------------------
jobs:
- deployment: Build${{ parameters.environmentName }}Application
  displayName: Initialize ${{ parameters.environmentName }}Build App
  environment: ${{ parameters.environmentName }}

- job: Build${{ parameters.environmentName }}LogicApp
  displayName: Build ${{ parameters.environmentName }} Application

  variables:
    - group: ${{ parameters.variableGroupName }}
    - name: projectName
    - name: environment
      value: ${{ parameters.environment }}
    - name: environmentLower
      value: ${{ lower(parameters.environment) }}
    - name: artifactFolderName
      value: 'App'
    - name: artifactName
      value: 'LA.zip'

  steps:
  - bash: |
      runDateTime=$(echo $(date '+%Y%m%d-%H%M%S'))
      echo "##vso[task.setvariable variable=runDateTime]$runDateTime"
      echo "runDateTime=$runDateTime"
    displayName: 'Create Variables'
    continueOnError: true

  - task: CmdLine@2
    inputs:
      script: |
        echo "runDateTime=$(runDateTime)"
        echo "solution=$(solution)"
        echo "artifactFolderName=$(artifactFolderName)"
        echo "artifactName=$(artifactName)"
        echo "Directory of System.DefaultWorkingDirectory:"
        tree $(System.DefaultWorkingDirectory)
        dir $(System.DefaultWorkingDirectory) /s
    displayName: 'Display Variables'

  - task: CopyFiles@2
    displayName: 'Create project folder'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: |
        Workflows/**
      TargetFolder: 'project_output'

  - task: Bash@3
    displayName: 'Swap local settings files with Azure versions'
    inputs:
      targetType: 'inline'
      workingDirectory: '$(System.DefaultWorkingDirectory)/project_output/Workflows'
      script: |
        mv azure.parameters.json parameters.json
        mv azure.connections.json connections.json

  - task: ArchiveFiles@2
    displayName: 'Create project zip'
    inputs:
      rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output/Workflows'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
      replaceExistingArchive: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish project zip artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/$(artifactName)'
      artifact: '$(artifactFolderName)'
      publishLocation: 'pipeline'
