# ----------------------------------------------------------------------------------------------------
# Template to deploy a logic app standard to a Function App
# ----------------------------------------------------------------------------------------------------
parameters: 
  stageName: ''
  stageDisplayName: ''
  variableGroupName: ''
  azureSubscription: ''
  environment: ''
  triggerFrequency: ''
  artifactName: ''

# ----------------------------------------------------------------------------------------------------
stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}

    jobs:
    - deployment: logic_app_deploy
      displayName: 'Deploy Logic App'
      environment: ${{ parameters.environment }}

      variables:
      - group: ${{ parameters.variableGroupName }}
      - name: stageName
        value: ${{ parameters.stageName }}
      - name: environment
        value: ${{ parameters.environment }}
      - name: triggerFrequency
        value: ${{ parameters.triggerFrequency }}
      - name: artifactFolderName
        value: 'App'

      strategy:
        runOnce:
          deploy:
            steps:
            - bash: |
                LOGIC_APP_NAME2="$('$(appPrefix)-demo-logic-app-$(environment)"
                RESOURCEGROUPNAME2="rg_logic_demo_$(environment)"
                echo "##vso[task.setvariable variable=LOGIC_APP_NAME2]$LOGIC_APP_NAME2"
                echo "##vso[task.setvariable variable=RESOURCEGROUPNAME2]$RESOURCEGROUPNAME2"

            - bash: |
                echo "RESOURCEGROUPNAME2=$(RESOURCEGROUPNAME2)"
                echo "LOGIC_APP_NAME2=$(LOGIC_APP_NAME2)"
                echo "azureSubscription=$(azureSubscription)"
                echo "region=$(region)"
                echo "resourceGroupName=$(resourceGroupName)"
                echo "environment=$(environment)"
                echo "appPrefix=$(appPrefix)"
                echo "logicAppName=$(logicAppName)"
                echo "triggerFrequency=$(triggerFrequency)"
                echo "Pipeline.Workspace=$(Pipeline.Workspace)"
                tree $(Pipeline.Workspace)
              displayName: 'Display Variables'
              continueOnError: true

            - task: AzureFunctionApp@1
              displayName: 'Deploy Logic App Zip'
              retryCountOnTaskFailure: 2
              inputs:
                azureSubscription: $(azureSubscription)
                appType: 'functionApp'
                appName: $(logicAppName)
                package: '$(Pipeline.Workspace)/$(artifactFolderName)/$(artifactName)'
                deploymentMethod: 'zipDeploy'
                AppSettings: '-TRIGGER_FREQUENCY $(triggerFrequency)'