# ------------------------------------------------------------------------------------------------------------------------
# Pipeline to deploy Logic Application to existing Function App
# ------------------------------------------------------------------------------------------------------------------------
# Note: This pipeline needs a variable group "LogicAppDemo"
#  See ../Docs/VariableGroups.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: 'ubuntu-latest'

# ----------------------------------------------------------------------------------------------------
trigger:
  branches:
    include:
    - main
  paths:
    include:
      - Workflows/*

# ----------------------------------------------------------------------------------------------------
stages:
- template: pipes/logicstd-only-pipeline-template.yml
  parameters:
    variableGroupName: 'LogicAppDemo'
    environments: ['DEV','PROD']  # ['DEV'] or ['DEV','QA'] or ['DEV','QA','PROD']
