# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy Azure Resources Only
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: template.deploy.infra
run-name: Deploy Infra
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string
      location:
        required: false
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Create Infra
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.envCode }}
    
    env:
      generatedAppEnvName: ${{ secrets.APP_NAME }}-${{ inputs.envCode }}
      generatedResourceGroupName: rg-${{ secrets.APP_NAME }}-${{ inputs.envCode }}

    steps:
    - name: Display Variables
      run: |-
        echo "generatedAppEnvName=${{ env.generatedAppEnvName }}"
        echo "generatedResourceGroupName=${{ env.generatedResourceGroupName }}"
        echo "appName=${{ secrets.APP_NAME }}"
        echo "location=${{ inputs.location }}"
        echo "Resource Group Command:"
        echo "  az group create --name ${{ env.generatedResourceGroupName }} --location ${{ inputs.location }} --tags Application=${{ secrets.APP_NAME }} Environment=${{ inputs.envCode }}"
        echo "Bicep Deploy Sample Command:"
        echo "  az deployment group create -n main-deploy-${{ env.runDateTimeZ }} --resource-group ${{ env.generatedResourceGroupName }} --template-file 'main.bicep' --parameters environment=${{ inputs.envCode }} location=${{ inputs.location }} appName=${{ secrets.APP_NAME }} keyVaultOwnerUserId=${{ env.keyVaultOwnerUserId }}"
        echo "Pipeline Workspace Directory Contents:"
        tree ${{ env.GITHUB_ACTION_PATH }}
      continue-on-error: true

    - name: Checkout Code
      uses: actions/checkout@main

    - name: List Files
      run: 
        tree ${{ env.GITHUB_ACTION_PATH }}
      continue-on-error: true

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create Resource Group
      run: 
        az group create --name ${{ env.generatedResourceGroupName }} --location ${{ inputs.location }} --tags Environment=${{ inputs.envCode }} Application=${{ secrets.APP_NAME }}

    - name: Deploy Azure Resources
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.generatedResourceGroupName }}
        template: infra/Bicep/main.bicep
        parameters: >
          environmentCode=${{ inputs.envCode }}
          location=${{ inputs.location }}
          appName=${{ secrets.APP_NAME }}
          keyVaultOwnerUserId=${{ secrets.KEYVAULT_OWNER_USERID }}
      continue-on-error: true
      # The Bicep files in this project get these warnings... not sure how to resolve this as 
      # these properties are needed and work fine, so mark this step as ignore errors for now...
      #   storageaccount.bicep(79,5)  : Warning BCP187: The property "kind" does not exist in the resource definition, although it might still be valid. If this is an inaccuracy in the documentation, please report it to the Bicep Team. [https://aka.ms/bicep-type-issues]
      #   storageaccount.bicep(84,13) : Warning use-resource-id-functions: If property "id" represents a resource ID, it must use a symbolic resource reference, be a parameter or start with one of these functions: extensionResourceId, guid, if, reference, resourceId, subscription, subscriptionResourceId, tenantResourceId. [https://aka.ms/bicep/linter/use-resource-id-functions]
      #   storageaccountroles.bicep(29,33) : Warning BCP081: Resource type "Microsoft.Web/connections/accessPolicies@2016-06-01" does not have types available.      